### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by nichujie** [DD2480-G12/a1-decide#2]
* Fancy badges (optional)
* Project description
* Setup & Installation
* File tree & description of main files
* Basic Workflow & Regulations
  * Link to issues
  * Commit message ([ref](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit))
  * Pull request (at least 2 approval), keep all commits (not squash)
* Statement of contribution...

**Comment by ekner** [comment]
According to the assignment description, I would say only "Project description", "Basic Workflow & Regulations" and "Statement of contributions" are necessary. What do you think?
